// <auto-generated />
namespace Movie_App_2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class reviewersmovies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reviewersmovies));
        
        string IMigrationMetadata.Id
        {
            get { return "202202110926035_reviewers-movies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
